---
name: Semantic Release

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

on:
  workflow_call:
    inputs:
      node_version:
        description: Node.js version for actions/setup-node
        type: string
        required: true
      environment:
        description: GitHub environment
        required: false
        type: string
      npm_client:
        description: npm client to use (npm or yarn)
        type: string
        default: "yarn"
      npm_client_production_flag:
        description: Npm client production flag
        type: string
        required: false
        default: "--frozen-lockfile"
      yarn_version:
        description: yarn version (1 or 4)
        type: string
        default: "1"
        required: false
      npm_registry_url:
        type: string
        description: NPM Registry URL for publishing
        default: "https://registry.npmjs.org"
        required: false
      working_directory:
        type: string
        description: Working directory for running commands (e.g., for monorepos)
        default: "."
        required: false
    secrets:
      GH_AUTH_TOKEN:
        description: GitHub token for creating releases, tags, and updating CHANGELOG
        required: true
      NPM_TOKEN:
        description: NPM authentication token for publishing
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_AUTH_TOKEN }}

      - name: Node Base actions
        uses: loash-industries/public-workflows/.github/actions/node-base-actions@v0.1.0
        with:
          node_version: ${{ inputs.node_version }}
          npm_client: ${{ inputs.npm_client }}
          npm_client_production_flag: ${{ inputs.npm_client_production_flag }}
          node_modules_cache_key_prefix: node-modules-release
          yarn_version: ${{ inputs.yarn_version }}
          working_directory: ${{ inputs.working_directory }}

      - name: Configure npm registry
        working-directory: ${{ inputs.working_directory }}
        run: |
          registry=$(echo "${{ inputs.npm_registry_url }}" | sed 's|https:||')
          echo "${registry}/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      - name: Build package
        working-directory: ${{ inputs.working_directory }}
        run: ${{ inputs.npm_client }} run build

      - name: Release
        working-directory: ${{ inputs.working_directory }}
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
